services:
  front:
    build:
      context: ./front
      dockerfile: dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    networks:
      - dev-network

  back:
    build:
      context: ./back
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - dev-network

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./back/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - front
      - back
    networks:
      - dev-network

volumes:
  db_data:
  postgres_data:

networks:
  dev-network:
    driver: bridge