FROM node:20-alpine

WORKDIR /app

# Copy only the dependencies files to optimize the Docker cache
COPY package*.json ./

# Install all dependencies, including devDependencies
RUN npm install

# Copy the rest of the project files
COPY . .

# Build the application
RUN npm run build
