FROM node:20-alpine

WORKDIR /app

# Copy only the dependencies files to optimize the Docker cache
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the project files
COPY . .

# Expose the port used by Vite
EXPOSE 5173

# starts the development server
CMD ["npm", "run", "dev"] 